[features]
seeds = false
skip-lint = false
[programs.localnet]
cactus = "6CDCUqzb1MQnEXaxhHNqXV2s1f9qChJ3GyXQwcH9Fp93"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/darraghmahns/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

